"""Trading and settlement calendars: business days, holiday rules, business-day conventions and trading sessions.

A calendar answers four questions the engine and the swap schedules need: *is this a business day*, *what is the next or previous one*, *how do I adjust a date that falls on a
holiday* (the ISDA conventions ``following``, ``modified_following``, ``preceding``, ``modified_preceding``) and *when does the session open and close*. Holidays are generated by
rule for any year (fixed dates with the Saturday-to-Friday and Sunday-to-Monday observance, n-th weekdays, Easter-based days), so no holiday list needs to be maintained.

Built-in calendars: ``24x7`` (crypto), ``WEEKDAY`` (Monday to Friday, no holidays), ``US`` (NYSE-style), ``TARGET`` (euro settlement), ``GBLO`` (London) and ``JOINT`` calendars made
by combining any of them (a date is a business day only if it is one in every member, the convention for cross-currency swaps).

The holiday rules are a faithful approximation of the exchange schedules, not a vendor feed: ad-hoc closures (state funerals, weather, one-off bank holidays) are not in them. Pass
``extra_holidays`` to add them.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from functools import lru_cache
from zoneinfo import ZoneInfo

import pandas as pd

CONVENTIONS = ("following", "modified_following", "preceding", "modified_preceding", "none")


def easter_sunday(year: int) -> dt.date:
    """Gregorian Easter (the anonymous Meeus/Jones/Butcher algorithm)."""
    a, b, c = year % 19, year // 100, year % 100
    d, e = b // 4, b % 4
    f = (b + 8) // 25
    g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30
    i, k = c // 4, c % 4
    l = (32 + 2 * e + 2 * i - h - k) % 7                                    # noqa: E741
    m = (a + 11 * h + 22 * l) // 451
    month = (h + l - 7 * m + 114) // 31
    day = (h + l - 7 * m + 114) % 31 + 1
    return dt.date(year, month, day)


def nth_weekday(year: int, month: int, weekday: int, n: int) -> dt.date:
    """The ``n``-th (1-based) ``weekday`` (Monday = 0) of the month; ``n = -1`` is the last one."""
    if n > 0:
        first = dt.date(year, month, 1)
        return first + dt.timedelta(days=(weekday - first.weekday()) % 7 + 7 * (n - 1))
    nxt = dt.date(year + (month == 12), month % 12 + 1, 1)
    last = nxt - dt.timedelta(days=1)
    return last - dt.timedelta(days=(last.weekday() - weekday) % 7)


def observed(day: dt.date) -> dt.date:
    """US observance: a Saturday holiday is taken on the Friday, a Sunday holiday on the Monday."""
    if day.weekday() == 5:
        return day - dt.timedelta(days=1)
    if day.weekday() == 6:
        return day + dt.timedelta(days=1)
    return day


def _substitute(day: dt.date, taken: set[dt.date]) -> dt.date:
    """UK substitution: a holiday on a weekend moves to the next free weekday."""
    while day.weekday() >= 5 or day in taken:
        day += dt.timedelta(days=1)
    return day


def us_holidays(year: int) -> set[dt.date]:
    out = {observed(dt.date(year, 1, 1)), nth_weekday(year, 1, 0, 3), nth_weekday(year, 2, 0, 3), easter_sunday(year) - dt.timedelta(days=2), nth_weekday(year, 5, 0, -1),
           observed(dt.date(year, 7, 4)), nth_weekday(year, 9, 0, 1), nth_weekday(year, 11, 3, 4), observed(dt.date(year, 12, 25))}
    if year >= 2022:
        out.add(observed(dt.date(year, 6, 19)))
    return {d for d in out if d.year == year}                                # a New Year's Day observed on 31 December belongs to the next year's list


def target_holidays(year: int) -> set[dt.date]:
    e = easter_sunday(year)
    return {dt.date(year, 1, 1), e - dt.timedelta(days=2), e + dt.timedelta(days=1), dt.date(year, 5, 1), dt.date(year, 12, 25), dt.date(year, 12, 26)}


def gb_holidays(year: int) -> set[dt.date]:
    e = easter_sunday(year)
    taken: set[dt.date] = {e - dt.timedelta(days=2), e + dt.timedelta(days=1), nth_weekday(year, 5, 0, 1), nth_weekday(year, 5, 0, -1), nth_weekday(year, 8, 0, -1)}
    new_year = _substitute(dt.date(year, 1, 1), taken)
    taken.add(new_year)
    christmas = _substitute(dt.date(year, 12, 25), taken)
    taken.add(christmas)
    taken.add(_substitute(dt.date(year, 12, 26), taken))
    return taken


HOLIDAY_RULES = {"24x7": lambda y: set(), "WEEKDAY": lambda y: set(), "US": us_holidays, "TARGET": target_holidays, "GBLO": gb_holidays}
WEEKMASKS = {"24x7": (True,) * 7}


@dataclass(frozen=True)
class Session:
    """A daily trading session: local ``open`` and ``close`` times (``HH:MM``) in time zone ``tz``. ``overnight=True`` means the close is on the next calendar day."""

    open: str = "09:30"
    close: str = "16:00"
    tz: str = "America/New_York"
    overnight: bool = False

    def bounds(self, day) -> tuple[pd.Timestamp, pd.Timestamp]:
        """The UTC open and close of the session that starts on local date ``day`` (returned tz-naive, UTC, the engine's convention)."""
        day = pd.Timestamp(day).date()
        zone = ZoneInfo(self.tz)
        oh, om = map(int, self.open.split(":"))
        ch, cm = map(int, self.close.split(":"))
        start = dt.datetime(day.year, day.month, day.day, oh, om, tzinfo=zone)
        end_day = day + dt.timedelta(days=1) if self.overnight else day
        end = dt.datetime(end_day.year, end_day.month, end_day.day, ch, cm, tzinfo=zone)
        utc = ZoneInfo("UTC")
        return pd.Timestamp(start.astimezone(utc)).tz_localize(None), pd.Timestamp(end.astimezone(utc)).tz_localize(None)


@dataclass(frozen=True)
class TradingCalendar:
    """Business days for one market (or a joint calendar of several)."""

    name: str = "WEEKDAY"
    weekmask: tuple = (True, True, True, True, True, False, False)       # Monday .. Sunday
    members: tuple = ()                                                    # names of the calendars a JOINT calendar combines
    extra_holidays: frozenset = field(default_factory=frozenset)
    session: Session | None = None

    def _rule(self, year: int) -> set[dt.date]:
        if self.members:
            out: set[dt.date] = set()
            for m in self.members:
                out |= get_calendar(m)._rule(year)
            return out
        return set(HOLIDAY_RULES.get(self.name, HOLIDAY_RULES["WEEKDAY"])(year))

    def holidays(self, year: int) -> set[dt.date]:
        return self._rule(year) | {d for d in self.extra_holidays if d.year == year}

    def _weekmask(self) -> tuple:
        if self.members:
            return tuple(all(get_calendar(m)._weekmask()[i] for m in self.members) for i in range(7))
        return WEEKMASKS.get(self.name, self.weekmask)

    def is_business_day(self, day) -> bool:
        d = pd.Timestamp(day).date()
        if not self._weekmask()[d.weekday()]:
            return False
        if self.members:                                                    # every member must be open (their holidays are the union)
            return all(get_calendar(m).is_business_day(d) for m in self.members) and d not in self.extra_holidays
        return d not in self.holidays(d.year)

    def next_business_day(self, day, include_self: bool = True) -> pd.Timestamp:
        d = pd.Timestamp(day).normalize()
        if not include_self:
            d += pd.Timedelta(days=1)
        while not self.is_business_day(d):
            d += pd.Timedelta(days=1)
        return d

    def previous_business_day(self, day, include_self: bool = True) -> pd.Timestamp:
        d = pd.Timestamp(day).normalize()
        if not include_self:
            d -= pd.Timedelta(days=1)
        while not self.is_business_day(d):
            d -= pd.Timedelta(days=1)
        return d

    def adjust(self, day, convention: str = "modified_following") -> pd.Timestamp:
        """Move ``day`` off a non-business day by an ISDA convention. ``modified_*`` never crosses a month end (it reverses direction instead)."""
        if convention not in CONVENTIONS:
            raise ValueError(f"convention must be one of {CONVENTIONS}")
        d = pd.Timestamp(day).normalize()
        if convention == "none" or self.is_business_day(d):
            return d
        if convention in ("following", "modified_following"):
            moved = self.next_business_day(d)
            if convention == "modified_following" and moved.month != d.month:
                moved = self.previous_business_day(d)
            return moved
        moved = self.previous_business_day(d)
        if convention == "modified_preceding" and moved.month != d.month:
            moved = self.next_business_day(d)
        return moved

    def add_business_days(self, day, n: int) -> pd.Timestamp:
        """``n`` business days after (``n > 0``) or before (``n < 0``) ``day``; ``day`` itself need not be a business day."""
        d = pd.Timestamp(day).normalize()
        step = 1 if n >= 0 else -1
        remaining = abs(int(n))
        while remaining:
            d += pd.Timedelta(days=step)
            if self.is_business_day(d):
                remaining -= 1
        return d

    def business_days(self, start, end) -> pd.DatetimeIndex:
        days = pd.date_range(pd.Timestamp(start).normalize(), pd.Timestamp(end).normalize(), freq="D")
        return pd.DatetimeIndex([d for d in days if self.is_business_day(d)])

    def business_days_between(self, start, end) -> int:
        """Business days in ``(start, end]``."""
        return max(len(self.business_days(start, end)) - int(self.is_business_day(start)), 0)

    def session_bounds(self, day) -> tuple[pd.Timestamp, pd.Timestamp]:
        if self.session is None:
            d = pd.Timestamp(day).normalize()
            return d, d + pd.Timedelta(days=1)
        return self.session.bounds(day)


@lru_cache(maxsize=None)
def get_calendar(name: str) -> TradingCalendar:
    """A built-in calendar by name; ``"US+TARGET"`` is the joint calendar of both."""
    if "+" in name:
        return TradingCalendar(name=name, members=tuple(sorted(p.strip() for p in name.split("+"))))
    if name not in HOLIDAY_RULES:
        raise KeyError(f"unknown calendar '{name}'; built-in: {sorted(HOLIDAY_RULES)} (combine with '+')")
    sessions = {"US": Session("09:30", "16:00", "America/New_York"), "TARGET": Session("09:00", "17:00", "Europe/Frankfurt"), "GBLO": Session("08:00", "16:30", "Europe/London"),
                "24x7": Session("00:00", "00:00", "UTC", overnight=True)}
    return TradingCalendar(name=name, session=sessions.get(name))


def joint_calendar(*names: str) -> TradingCalendar:
    return get_calendar("+".join(names))
