"""The research report must agree with the tables it claims to summarise.

A report is a snapshot of numbers that are regenerated by a pipeline. Without
a check, the two drift apart the first time a parameter changes, and a reader
has no way to tell. These tests parse the headline figures out of the report's
own markdown and compare them against the generated CSVs.

They skip cleanly when the pipeline has not been run, so a fresh checkout
still has a green suite.
"""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "reports" / "tables"
REPORT = ROOT / "reports" / "research_report.md"

# (label in the report, table, index, column, tolerance)
CLAIMS = [
    ("M0 equal weight Sharpe", "stage12_final_comparison.csv", "M0_equal_weight", "sharpe", 0.69, 0.0051),
    ("M1 inverse vol Sharpe", "stage12_final_comparison.csv", "M1_inverse_vol", "sharpe", 0.85, 0.0051),
    ("M2 risk parity Sharpe", "stage12_final_comparison.csv", "M2_risk_parity", "sharpe", 0.79, 0.0051),
    ("M3 momentum Sharpe", "stage12_final_comparison.csv", "M3_momentum", "sharpe", 0.31, 0.0051),
    ("M4 mean reversion Sharpe", "stage12_final_comparison.csv", "M4_mean_reversion", "sharpe", -0.24, 0.0051),
    ("M9 mean-CVaR Sharpe", "stage12_final_comparison.csv", "M9_mean_cvar", "sharpe", 0.81, 0.0051),
    ("SPY Sharpe", "stage12_final_comparison.csv", "SPY_buy_hold", "sharpe", 0.65, 0.0051),
    ("PC1 explained variance", "stage02_pca_summary.csv", "PC1", "explained_variance", 0.407, 0.0005),
    ("holdout momentum Sharpe", "stage12_final_holdout.csv", "M3_momentum", "sharpe", -0.15, 0.0051),
    ("holdout reversion Sharpe", "stage12_final_holdout.csv", "M4_mean_reversion", "sharpe", -0.31, 0.0051),
    ("holdout SPY Sharpe", "stage12_final_holdout.csv", "SPY_buy_hold", "sharpe", 0.76, 0.0051),
    ("momentum breakeven cost (bps)", "stage06_breakeven_costs.csv", "M3_momentum", "breakeven_bps", 28.9, 0.051),
    ("mean-reversion breakeven cost (bps)", "stage06_breakeven_costs.csv", "M4_mean_reversion", "breakeven_bps", -1.2, 0.051),
    ("combined breakeven cost (bps)", "stage06_breakeven_costs.csv", "M5_momentum_plus_mr", "breakeven_bps", 8.8, 0.051),
]


def _table(name: str) -> pd.DataFrame:
    path = TABLES / name
    if not path.exists():
        pytest.skip(f"{name} not generated; run `python -m experiments.run_all`")
    return pd.read_csv(path, index_col=0)


@pytest.mark.parametrize("label,table,row,column,claimed,tolerance", CLAIMS)
def test_report_claim_matches_generated_table(label, table, row, column, claimed, tolerance):
    frame = _table(table)
    if row not in frame.index:
        pytest.skip(f"{row} not present in {table}")
    actual = float(frame.loc[row, column])
    assert actual == pytest.approx(claimed, abs=tolerance), (
        f"{label}: report says {claimed}, {table} says {actual:.4f}"
    )


def test_every_var_configuration_fails_its_backtest():
    """Section 10.2's central claim: zero of eight configurations pass."""
    path = TABLES / "stage09_var_backtest.csv"
    if not path.exists():
        pytest.skip("stage 9 not run")
    frame = pd.read_csv(path)
    assert int((frame["verdict"] == "pass").sum()) == 0
    assert len(frame) >= 8


def test_no_pair_is_cointegrated():
    """Section 13A.1's central claim."""
    path = TABLES / "stage14_pairs_screen.csv"
    if not path.exists():
        pytest.skip("stage 14 not run")
    frame = pd.read_csv(path)
    assert int(frame["cointegrated"].sum()) == 0


def test_leakage_suite_passed_and_the_control_was_caught():
    path = TABLES / "stage11_leakage_tests.csv"
    if not path.exists():
        pytest.skip("stage 11 not run")
    frame = pd.read_csv(path)
    real = frame[~frame["strategy"].str.startswith("CONTROL")]
    control = frame[frame["strategy"].str.startswith("CONTROL")]
    assert bool(real["passed"].all()), "a production strategy failed the look-ahead test"
    assert len(control) > 0 and not bool(control["passed"].any()), \
        "the deliberately broken control strategy was not caught"


def test_report_states_its_data_version_and_config_fingerprint():
    if not REPORT.exists():
        pytest.skip("report not written")
    text = REPORT.read_text(encoding="utf-8")
    assert re.search(r"Data version:\*\* `[0-9a-f]{6,}`", text)
    assert re.search(r"Config fingerprint:\*\* `[0-9a-f]{6,}`", text)


def test_every_figure_has_a_stated_research_question():
    figures = ROOT / "reports" / "figures"
    if not figures.exists() or not list(figures.glob("*.png")):
        pytest.skip("figures not generated")
    missing = [p.name for p in figures.glob("*.png") if not p.with_suffix(".txt").exists()]
    assert not missing, f"figures without a research question: {missing}"


def test_notebook_is_valid_and_imports_only_public_api():
    """The tour notebook must be parseable and must not reach into internals."""
    import json

    path = ROOT / "notebooks" / "01_platform_tour.ipynb"
    if not path.exists():
        pytest.skip("notebook not present")
    notebook = json.loads(path.read_text(encoding="utf-8"))
    assert notebook["nbformat"] >= 4
    code = "\n".join(
        "".join(cell["source"]) for cell in notebook["cells"] if cell["cell_type"] == "code"
    )
    assert code.strip(), "notebook has no code"
    # Private helpers are an implementation detail; a tour should not depend on them.
    assert "import _" not in code and "._" not in code.replace("df._", "")
    compile(code, str(path), "exec")


def _report_table_rows(heading: str) -> list[list[str]]:
    """Cells of the markdown table that follows ``heading`` in the report."""
    text = REPORT.read_text(encoding="utf-8").replace("\u2212", "-").replace("**", "")
    block = text.split(heading, 1)[1]
    rows = []
    for line in block.splitlines()[1:]:
        if not line.startswith("|"):
            if rows:
                break
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if set(cells[0]) <= set("-:"):
            continue
        rows.append(cells)
    return rows[1:]                                           # drop the header row


def test_headline_table_matches_the_final_comparison_cell_by_cell():
    """Every number in Section 1.4 is the stage-12 table's value, rounded as printed."""
    if not REPORT.exists() or not (TABLES / "stage12_final_comparison.csv").exists():
        pytest.skip("report or tables not generated")
    frame = pd.read_csv(TABLES / "stage12_final_comparison.csv", index_col=0)
    keys = {"SPY buy & hold": "SPY_buy_hold", "M0 Equal weight": "M0_equal_weight", "M1 Inverse volatility": "M1_inverse_vol",
            "M2 Risk parity": "M2_risk_parity", "M3 Momentum": "M3_momentum", "M4 Mean reversion": "M4_mean_reversion",
            "M5 Momentum + reversion": "M5_momentum_plus_mr", "M6 Combined alpha + MVO": "M6_combined_alpha_mvo",
            "M7 + shrinkage covariance": "M7_combined_alpha_shrinkage_mvo", "M8 Black-Litterman": "M8_black_litterman",
            "M9 Mean-CVaR": "M9_mean_cvar"}
    checked = 0
    for cells in _report_table_rows("### 1.4 The headline table"):
        if cells[0] not in keys:
            continue
        r = frame.loc[keys[cells[0]]]
        expected = [100 * r["cagr"], 100 * r["ann_vol"], r["sharpe"], r["sortino"], 100 * r["max_drawdown"], 100 * r["cvar_95"],
                    r["ann_turnover"], 1e4 * r["ann_cost_drag"]]
        shown = [float(c.replace("%", "").replace("x", "").replace(" bp", "")) for c in cells[1:9]]
        decimals = [1, 1, 2, 2, 1, 2, 1, 0]
        for value, text, d, name in zip(expected, shown, decimals, ["CAGR", "vol", "Sharpe", "Sortino", "max DD", "CVaR", "turnover", "cost drag"]):
            assert abs(value - text) <= 0.5 * 10 ** -d + 1e-9, f"{cells[0]} {name}: report {text}, table {value:.4f}"
        checked += 1
    assert checked == len(keys)


def test_walk_forward_and_holdout_tables_match_their_csvs():
    if not REPORT.exists() or not (TABLES / "stage11_walk_forward_summary.csv").exists():
        pytest.skip("report or tables not generated")
    wf = pd.read_csv(TABLES / "stage11_walk_forward_summary.csv", index_col=0)
    names = {"M1 inverse volatility": "M1_inverse_vol", "M2 risk parity": "M2_risk_parity", "M9 mean-CVaR": "M9_mean_cvar",
             "M0 equal weight": "M0_equal_weight", "M3 momentum": "M3_momentum", "M5 combined alpha": "M5_momentum_plus_mr"}
    for cells in _report_table_rows("### 12.3 Walk-forward"):
        assert abs(float(cells[3]) - wf.loc[names[cells[0]], "sharpe"]) <= 0.0005 + 1e-9, cells
    ho = pd.read_csv(TABLES / "stage12_final_holdout.csv", index_col=0)
    hold = {"SPY buy & hold": "SPY_buy_hold", "M0 equal weight": "M0_equal_weight", "M2 risk parity": "M2_risk_parity",
            "M1 inverse volatility": "M1_inverse_vol", "M7 shrinkage MVO": "M7_combined_alpha_shrinkage_mvo", "M9 mean-CVaR": "M9_mean_cvar",
            "M8 Black-Litterman": "M8_black_litterman", "M5 combined alpha": "M5_momentum_plus_mr", "M3 momentum": "M3_momentum",
            "M4 mean reversion": "M4_mean_reversion"}
    for cells in _report_table_rows("2022-01-03 to 2026-09-21:"):
        assert abs(float(cells[3]) - ho.loc[hold[cells[0]], "sharpe"]) <= 0.005 + 1e-9, cells
