"""The research report must agree with the tables it claims to summarise.

A report is a snapshot of numbers that are regenerated by a pipeline. Without
a check, the two drift apart the first time a parameter changes, and a reader
has no way to tell. These tests parse the headline figures out of the report's
own markdown and compare them against the generated CSVs.

They skip cleanly when the pipeline has not been run, so a fresh checkout
still has a green suite.
"""

from __future__ import annotations

import re
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "reports" / "tables"
REPORT = ROOT / "reports" / "research_report.md"

# (label in the report, table, index, column, tolerance)
CLAIMS = [
    ("M0 equal weight Sharpe", "stage12_final_comparison.csv", "M0_equal_weight", "sharpe", 0.70, 0.02),
    ("M1 inverse vol Sharpe", "stage12_final_comparison.csv", "M1_inverse_vol", "sharpe", 0.87, 0.02),
    ("M2 risk parity Sharpe", "stage12_final_comparison.csv", "M2_risk_parity", "sharpe", 0.80, 0.02),
    ("M3 momentum Sharpe", "stage12_final_comparison.csv", "M3_momentum", "sharpe", 0.30, 0.02),
    ("M4 mean reversion Sharpe", "stage12_final_comparison.csv", "M4_mean_reversion", "sharpe", -0.24, 0.02),
    ("M9 mean-CVaR Sharpe", "stage12_final_comparison.csv", "M9_mean_cvar", "sharpe", 0.81, 0.02),
    ("SPY Sharpe", "stage12_final_comparison.csv", "SPY_buy_hold", "sharpe", 0.65, 0.02),
    ("PC1 explained variance", "stage02_pca_summary.csv", "PC1", "explained_variance", 0.407, 0.005),
    ("holdout momentum Sharpe", "stage12_final_holdout.csv", "M3_momentum", "sharpe", -0.166, 0.02),
    ("holdout reversion Sharpe", "stage12_final_holdout.csv", "M4_mean_reversion", "sharpe", -0.313, 0.02),
    ("holdout SPY Sharpe", "stage12_final_holdout.csv", "SPY_buy_hold", "sharpe", 0.762, 0.02),
]


def _table(name: str) -> pd.DataFrame:
    path = TABLES / name
    if not path.exists():
        pytest.skip(f"{name} not generated; run `python -m experiments.run_all`")
    return pd.read_csv(path, index_col=0)


@pytest.mark.parametrize("label,table,row,column,claimed,tolerance", CLAIMS)
def test_report_claim_matches_generated_table(label, table, row, column, claimed, tolerance):
    frame = _table(table)
    if row not in frame.index:
        pytest.skip(f"{row} not present in {table}")
    actual = float(frame.loc[row, column])
    assert actual == pytest.approx(claimed, abs=tolerance), (
        f"{label}: report says {claimed}, {table} says {actual:.4f}"
    )


def test_every_var_configuration_fails_its_backtest():
    """Section 10.2's central claim: zero of eight configurations pass."""
    path = TABLES / "stage09_var_backtest.csv"
    if not path.exists():
        pytest.skip("stage 9 not run")
    frame = pd.read_csv(path)
    assert int((frame["verdict"] == "pass").sum()) == 0
    assert len(frame) >= 8


def test_no_pair_is_cointegrated():
    """Section 13A.1's central claim."""
    path = TABLES / "stage14_pairs_screen.csv"
    if not path.exists():
        pytest.skip("stage 14 not run")
    frame = pd.read_csv(path)
    assert int(frame["cointegrated"].sum()) == 0


def test_leakage_suite_passed_and_the_control_was_caught():
    path = TABLES / "stage11_leakage_tests.csv"
    if not path.exists():
        pytest.skip("stage 11 not run")
    frame = pd.read_csv(path)
    real = frame[~frame["strategy"].str.startswith("CONTROL")]
    control = frame[frame["strategy"].str.startswith("CONTROL")]
    assert bool(real["passed"].all()), "a production strategy failed the look-ahead test"
    assert len(control) > 0 and not bool(control["passed"].any()), \
        "the deliberately broken control strategy was not caught"


def test_report_states_its_data_version_and_config_fingerprint():
    if not REPORT.exists():
        pytest.skip("report not written")
    text = REPORT.read_text(encoding="utf-8")
    assert re.search(r"Data version:\*\* `[0-9a-f]{6,}`", text)
    assert re.search(r"Config fingerprint:\*\* `[0-9a-f]{6,}`", text)


def test_every_figure_has_a_stated_research_question():
    figures = ROOT / "reports" / "figures"
    if not figures.exists() or not list(figures.glob("*.png")):
        pytest.skip("figures not generated")
    missing = [p.name for p in figures.glob("*.png") if not p.with_suffix(".txt").exists()]
    assert not missing, f"figures without a research question: {missing}"
