"""G-learning: reinforcement learning with an information cost, and the inverse problem (GIRL).

**G-learning** (Fox, Pakman and Tishby 2016; used for portfolios by Dixon and Halperin) regularises the value of a policy ``pi`` by its relative entropy from a *prior* policy ``pi_0`` (a benchmark, a default
behaviour, or what the agent did before), in units of ``1/beta``:

    value of pi = E[ sum_t gamma^t ( r_t - (1/beta) log (pi(a_t | s_t) / pi_0(a_t | s_t)) ) ].

The optimum satisfies a *soft* Bellman equation,

    G(s, a) = R(s, a) + gamma E[ F(s') ],        F(s) = (1/beta) log sum_a pi_0(a | s) exp(beta G(s, a)),        pi(a | s) = pi_0(a | s) exp(beta (G(s, a) - F(s))).

``beta -> infinity`` removes the information cost and gives ordinary Q-learning's greedy policy; ``beta -> 0`` makes it too costly to deviate and the policy is the prior. The sample version updates ``G``
toward ``r + gamma F(s')`` along trajectories generated by the current policy.

**GIRL** (the inverse problem): given demonstrations from an agent assumed to behave this way, find the reward. With a reward linear in features, ``R = Phi theta``, the likelihood of the observed
state-action pairs is that of the soft policy, ``prod pi_theta(a | s)``, which is maximised over ``theta``. The reward is identified only up to what leaves the policy unchanged (adding a function of the state
alone to a reward that has the same next-state distribution for every action, for example), so recovered rewards are compared through the policies they imply as well as directly.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import minimize
from scipy.special import logsumexp

from ..control.mdp import MDP
from .envs import TabularEnv


def soft_value(G: np.ndarray, prior: np.ndarray, beta: float) -> np.ndarray:
    """``F(s) = (1/beta) log sum_a pi_0(a|s) exp(beta G(s, a))``."""
    return logsumexp(beta * G + np.log(np.maximum(prior, 1e-300)), axis=1) / beta


def soft_policy(G: np.ndarray, prior: np.ndarray, beta: float) -> np.ndarray:
    z = beta * G + np.log(np.maximum(prior, 1e-300))
    return np.exp(z - logsumexp(z, axis=1, keepdims=True))


@dataclass
class SoftSolution:
    G: np.ndarray
    F: np.ndarray
    policy: np.ndarray
    iterations: int


def soft_value_iteration(mdp: MDP, prior: np.ndarray | None = None, beta: float = 5.0, tol: float = 1e-12, max_iter: int = 100000) -> SoftSolution:
    """The model-based solution of the soft Bellman equation (the target the sample-based G-learning is checked against)."""
    prior = np.full((mdp.n_states, mdp.n_actions), 1.0 / mdp.n_actions) if prior is None else np.asarray(prior, dtype=float)
    G = np.zeros((mdp.n_states, mdp.n_actions))
    for k in range(1, max_iter + 1):
        F = soft_value(G, prior, beta)
        G_new = mdp.q_values(F)
        if np.abs(G_new - G).max() < tol:
            G = G_new
            break
        G = G_new
    F = soft_value(G, prior, beta)
    return SoftSolution(G, F, soft_policy(G, prior, beta), k)


def g_learning(env: TabularEnv, prior: np.ndarray | None = None, beta: float = 5.0, episodes: int = 600, gamma: float = 0.9, alpha: float = 1.0, omega: float = 0.7, max_steps: int = 100,
               explore: float = 0.2, seed: int = 0) -> SoftSolution:
    """Sample-based G-learning: follow the current soft policy, move ``G(s, a)`` toward ``r + gamma F(s')`` with a step size ``alpha / (1 + visits)^omega``. With probability ``explore`` the action is uniformly
    random instead: the update does not depend on which action was taken, and without it actions the soft policy rarely picks keep their stale initial values, which ``F`` (a prior-weighted sum over all
    actions) still counts, leaving a bias that does not shrink (an error of 0.42 against 0.03 on the example in the tests)."""
    rng = np.random.default_rng(seed)
    S, A = env.n_states, env.n_actions
    prior = np.full((S, A), 1.0 / A) if prior is None else np.asarray(prior, dtype=float)
    G, n = np.zeros((S, A)), np.zeros((S, A))
    log_prior = np.log(np.maximum(prior, 1e-300))
    for ep in range(episodes):
        s = env.reset(seed=seed if ep == 0 else None)
        for _ in range(max_steps):
            z = beta * G[s] + log_prior[s]
            p = np.exp(z - z.max())
            a = int(rng.integers(A)) if explore and rng.random() < explore else int(rng.choice(A, p=p / p.sum()))
            s2, r, done = env.step(a)
            if done:
                F2 = 0.0
            else:
                z2 = beta * G[s2] + log_prior[s2]
                m = z2.max()
                F2 = (m + np.log(np.exp(z2 - m).sum())) / beta
            lr = alpha / (1.0 + n[s, a]) ** omega
            n[s, a] += 1
            G[s, a] += lr * (r + gamma * F2 - G[s, a])
            s = s2
            if done:
                break
    F = soft_value(G, prior, beta)
    return SoftSolution(G, F, soft_policy(G, prior, beta), episodes)


# ------------------------------------------------------------------------------------------------------------------ inverse
@dataclass
class GIRLResult:
    theta: np.ndarray
    reward: np.ndarray          # (S, A): Phi theta
    policy: np.ndarray
    log_likelihood: float
    success: bool


def demonstration_counts(trajectories: list, n_states: int, n_actions: int) -> np.ndarray:
    """``n[s, a]``: how often the demonstrator took action ``a`` in state ``s``. A trajectory is a list of ``(s, a)`` pairs."""
    n = np.zeros((n_states, n_actions))
    for traj in trajectories:
        for s, a in traj:
            n[int(s), int(a)] += 1
    return n


def girl(P: np.ndarray, features: np.ndarray, counts: np.ndarray, gamma: float = 0.9, beta: float = 1.0, prior: np.ndarray | None = None, l2: float = 1e-3, theta0: np.ndarray | None = None,
         max_iter: int = 200) -> GIRLResult:
    """Maximum-likelihood inverse reinforcement learning for a soft-optimal agent. ``P`` is ``(A, S, S)``, ``features`` is ``(S, A, K)``, ``counts`` the demonstrated ``(S, A)`` counts. The reward is
    ``features @ theta``; ``l2`` is a small ridge penalty that keeps the problem well posed when the data say little. The likelihood is the soft policy's, so the gradient is taken numerically."""
    P, X, n = np.asarray(P, dtype=float), np.asarray(features, dtype=float), np.asarray(counts, dtype=float)
    A, S, _ = P.shape
    K = X.shape[2]
    pri = np.full((S, A), 1.0 / A) if prior is None else np.asarray(prior, dtype=float)

    def neg_ll(theta):
        mdp = MDP(P, X @ theta, gamma)
        pol = soft_value_iteration(mdp, pri, beta, tol=1e-10).policy
        return -float((n * np.log(np.maximum(pol, 1e-300))).sum()) + l2 * float(theta @ theta)

    res = minimize(neg_ll, np.zeros(K) if theta0 is None else theta0, method="L-BFGS-B", options={"maxiter": max_iter})
    theta = res.x
    reward = X @ theta
    pol = soft_value_iteration(MDP(P, reward, gamma), pri, beta).policy
    return GIRLResult(theta, reward, pol, -float(res.fun), bool(res.success))


def mean_policy_kl(true: np.ndarray, learned: np.ndarray, weights: np.ndarray | None = None) -> float:
    """Average over states of ``KL(true || learned)`` (weighted by ``weights`` if given)."""
    kl = (true * (np.log(np.maximum(true, 1e-300)) - np.log(np.maximum(learned, 1e-300)))).sum(axis=1)
    w = np.full(len(kl), 1.0 / len(kl)) if weights is None else weights / weights.sum()
    return float(w @ kl)
