"""The tear sheet: one page that says what a strategy did, whether it survives scrutiny, and where it is fragile.

The markdown has a **red-flag list** generated by fixed rules, not by judgement: each rule is stated next to its result, so a
newcomer learns which questions to ask (does it beat a simple benchmark? does it hold in the final holdout? does the Sharpe
survive the number of ideas tried? is the model causal?) and a veteran can see the thresholds.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from ..utils.plotting import PALETTE, apply_style, save_figure

REGIME_COLOUR = {"Crisis": "#D55E00", "HighVol": "#E69F00", "LowVol": "#BBBBBB", "Inflation": "#CC79A7", "Deflation": "#56B4E9"}


def red_flags(result) -> list[dict]:
    """Fixed rules, each with its threshold and observed value. ``flag`` is True when the rule is violated."""
    m, v, t = result.metrics, result.validation, result.tables
    flags = []

    def add(rule, observed, flag, why):
        flags.append({"rule": rule, "observed": observed, "flag": bool(flag), "why": why})

    add("Net Sharpe is positive", f"{m['sharpe']:+.2f}", m["sharpe"] <= 0, "A strategy that loses after costs has nothing to explain.")
    hold = t.get("by_sample", pd.DataFrame())
    if "final_holdout" in hold.index:
        add("Positive Sharpe in the final holdout", f"{hold.loc['final_holdout', 'sharpe']:+.2f}", hold.loc["final_holdout", "sharpe"] <= 0,
            "The holdout is the part of history least likely to have shaped the design.")
    bench = t.get("benchmarks", pd.DataFrame())
    if len(bench) and "p_value" in bench:
        for _, r in bench.dropna(subset=["p_value"]).iterrows():
            add(f"Beats {r['benchmark']} (paired bootstrap, p <= 0.10, positive difference)", f"diff {r['difference']:+.2f}, p = {r['p_value']:.2f}",
                not (r["p_value"] <= 0.10 and r["difference"] > 0), "A strategy should earn more per unit of risk than a rule that needs no forecasts.")
    add("Deflated Sharpe probability >= 0.95", f"{v['deflated_sharpe_probability']:.2f} with {v['n_trials']} trial(s)", v["deflated_sharpe_probability"] < 0.95,
        "The probability the Sharpe exceeds what the best of the ideas tried would show by chance.")
    gross = m["gross_sharpe"]
    add("Costs take less than half of the gross Sharpe", f"gross {gross:+.2f} -> net {m['sharpe']:+.2f}", gross > 0 and m["sharpe"] < 0.5 * gross,
        "High turnover strategies often die on costs.")
    add("Annual turnover below 10x", f"{m['ann_turnover']:.1f}x", m["ann_turnover"] > 10, "Costs scale with turnover; capacity shrinks with it.")
    add("Evaluation window of at least 8 years", f"{m['n_days'] / 252:.1f} years", m["n_days"] < 8 * 252, "Short windows cannot separate skill from one good regime.")
    caus = v.get("causality")
    if caus:
        failed = [k for k, c in caus.items() if not c["ok"]]
        add("Every model and regime detector passes the causality check", "all pass" if not failed else f"FAILED: {', '.join(failed)}", bool(failed),
            "Replacing the future with noise must not change anything in the past.")
    if "reliability" in t:
        add("Forecast beats the climatological Brier score", f"{m.get('forecast_brier', np.nan):.4f} vs {m.get('forecast_brier_climatology', np.nan):.4f}",
            not (m.get("forecast_brier", 1) < m.get("forecast_brier_climatology", 0)), "Probability forecasts should be better than always saying the base rate.")
    return flags


def _monthly(returns: pd.Series) -> pd.DataFrame:
    monthly = (1 + returns).resample("ME").prod() - 1
    return monthly.to_frame("r").assign(year=monthly.index.year, month=monthly.index.month).pivot(index="year", columns="month", values="r")


def _figure(result, path: Path) -> None:
    apply_style()
    net = result.window.dropna()
    fig, axes = plt.subplots(3, 3, figsize=(17, 12))
    ax = axes[0, 0]
    curve = (1 + net).cumprod()
    if result.regimes is not None:
        labels = result.regimes.hard_labels().reindex(curve.index)
        for name, colour in REGIME_COLOUR.items():
            mask = labels == name
            if mask.any() and name != "LowVol":
                ax.fill_between(curve.index, 0, 1, where=mask.to_numpy(), transform=ax.get_xaxis_transform(), color=colour, alpha=0.18, linewidth=0)
    ax.plot(curve.index, curve, color=PALETTE[0], linewidth=1.6, label=result.spec.name)
    for i, (name, b) in enumerate(result.benchmarks.items()):
        c = (1 + b.reindex(curve.index).fillna(0)).cumprod()
        ax.plot(c.index, c, color=PALETTE[1 + i], linewidth=1.0, label=name)
    ax.set_yscale("log")
    from matplotlib.ticker import FormatStrFormatter
    ax.yaxis.set_major_formatter(FormatStrFormatter("%.1f"))
    ax.yaxis.set_minor_formatter(FormatStrFormatter("%.1f"))
    ax.set_title("Growth of 1 (log); shaded = regimes")
    ax.legend(fontsize=7)
    ax = axes[0, 1]
    dd = curve / curve.cummax() - 1
    ax.fill_between(dd.index, dd, 0, color=PALETTE[0], alpha=0.5)
    ax.set_title(f"Drawdown (max {dd.min():.1%})")
    ax = axes[0, 2]
    roll = net.rolling(252).mean() / net.rolling(252).std() * np.sqrt(252)
    ax.plot(roll.index, roll, color=PALETTE[2], linewidth=1.1)
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title("Rolling 1-year Sharpe")
    ax = axes[1, 0]
    heat = _monthly(net)
    ax.imshow(heat.to_numpy(), cmap="RdBu", vmin=-0.08, vmax=0.08, aspect="auto")
    ax.set_yticks(range(len(heat.index))[::2], heat.index[::2], fontsize=7)
    ax.set_xticks(range(12), list("JFMAMJJASOND"))
    ax.set_title("Monthly returns")
    ax = axes[1, 1]
    group = result.tables["attribution_by_asset"]["asset_class"]
    by_class = result.weights.abs().T.groupby(group).sum().T.resample("ME").last()
    by_class = by_class.loc[curve.index[0]:]
    ax.stackplot(by_class.index, by_class.T.to_numpy(), labels=list(by_class.columns), colors=PALETTE[: by_class.shape[1]])
    ax.legend(fontsize=6, loc="upper left", ncol=2)
    ax.set_title("Gross exposure by asset class")
    ax = axes[1, 2]
    att = result.tables["attribution"]["return_points"]
    att = att[att.abs() > 1e-9]
    ax.barh(range(len(att)), att.to_numpy(), color=[PALETTE[3] if v < 0 else PALETTE[2] for v in att])
    ax.set_yticks(range(len(att)), [str(i)[:26] for i in att.index], fontsize=7)
    ax.axvline(0, color="black", linewidth=0.8)
    ax.set_title("Where the return came from (return points)")
    ax = axes[2, 0]
    if "reliability" in result.tables and len(result.tables["reliability"]):
        rel = result.tables["reliability"]
        ax.plot([0.3, 0.7], [0.3, 0.7], color="black", linestyle=":")
        ax.scatter(rel["predicted"], rel["realised"], s=np.clip(rel["n"] / rel["n"].max() * 200, 10, 200), color=PALETTE[0])
        ax.set_xlabel("Forecast P(up)")
        ax.set_ylabel("Realised frequency")
        ax.set_title("Is the confidence honest? (reliability)")
    else:
        ax.axis("off")
    ax = axes[2, 1]
    if "by_regime" in result.tables:
        br = result.tables["by_regime"]
        ax.bar(range(len(br)), br["sharpe"], color=[REGIME_COLOUR.get(i, "#888888") for i in br.index])
        ax.set_xticks(range(len(br)), br.index, fontsize=8)
        ax.axhline(0, color="black", linewidth=0.8)
        ax.set_title("Sharpe by regime")
    else:
        ax.axis("off")
    ax = axes[2, 2]
    sample = result.tables["by_sample"]
    if len(sample):
        ax.bar(range(len(sample)), sample["sharpe"], color=PALETTE[4])
        ax.set_xticks(range(len(sample)), [s.replace("_", "\n") for s in sample.index], fontsize=8)
        ax.axhline(0, color="black", linewidth=0.8)
        ax.set_title("Sharpe by sample (development / validation / holdout)")
    fig.suptitle(f"Tear sheet: {result.spec.name}   ({result.metrics['start']} to {result.metrics['end']}, net of costs)", fontsize=14, fontweight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    fig.savefig(path, dpi=110)
    plt.close(fig)


def _md_table(frame: pd.DataFrame, floatfmt="{:.3f}") -> str:
    if frame is None or len(frame) == 0:
        return "_none_\n"
    frame = frame.copy()
    header = "| " + " | ".join([frame.index.name or ""] + [str(c) for c in frame.columns]) + " |"
    rule = "|" + "---|" * (len(frame.columns) + 1)
    rows = ["| " + " | ".join([str(i)] + [floatfmt.format(x) if isinstance(x, (float, np.floating)) else str(x) for x in r]) + " |" for i, r in zip(frame.index, frame.to_numpy())]
    return "\n".join([header, rule, *rows]) + "\n"


def make_tearsheet(result, directory: Path, run_id: str = "") -> Path:
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    _figure(result, directory / "tearsheet.png")
    m, flags = result.metrics, red_flags(result)
    lines = [f"# Tear sheet: {result.spec.name}", "", f"Run `{run_id}` on `{result.bundle_name}`, {m['start']} to {m['end']} ({m['n_days'] / 252:.1f} years), all numbers net of costs unless stated.", "",
             "![tear sheet](tearsheet.png)", "", "## Headline", "",
             f"| Net Sharpe | CAGR | Volatility | Max drawdown | Gross Sharpe | Turnover | Cost drag |", "|---|---|---|---|---|---|---|",
             f"| {m['sharpe']:+.2f} | {m['cagr']:.1%} | {m['ann_vol']:.1%} | {m['max_drawdown']:.1%} | {m['gross_sharpe']:+.2f} | {m['ann_turnover']:.1f}x/yr | {m['ann_cost_bps']:.0f} bps/yr |", "",
             "## Red flags (fixed rules)", "", "| Rule | Observed | Result | Why it matters |", "|---|---|---|---|"]
    for f in flags:
        lines.append(f"| {f['rule']} | {f['observed']} | {'**FLAG**' if f['flag'] else 'ok'} | {f['why']} |")
    lines += ["", f"{sum(f['flag'] for f in flags)} of {len(flags)} rules flagged. A flag is a question, not a verdict.", "",
              "## Against simple benchmarks", "", _md_table(result.tables["benchmarks"].set_index("benchmark") if len(result.tables["benchmarks"]) else None),
              "## By sample", "", _md_table(result.tables["by_sample"])]
    if "by_regime" in result.tables:
        lines += ["## By regime", "", _md_table(result.tables["by_regime"])]
    lines += ["## Where the return came from", "", _md_table(result.tables["attribution"], "{:+.2f}"), "## By asset", "",
              _md_table(result.tables["attribution_by_asset"], "{:+.3f}")]
    forecast_keys = [k for k in m if k.startswith("forecast_")]
    if forecast_keys:
        lines += ["## Forecast quality", "", "| Measure | Value |", "|---|---|", *[f"| {k.replace('forecast_', '').replace('_', ' ')} | {m[k]:.4f} |" for k in forecast_keys]]
    lines += ["", "## Specification", "", "```yaml", __import__("yaml").safe_dump(result.spec.to_dict(), sort_keys=False).strip(), "```", ""]
    path = directory / "tearsheet.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
